### PR TITLE
Add neutral status

### PR DESCRIPTION
**Pull request by xarlio**
Neutral: ~~orange~~ black (light off)
Busy: red
Available: green

### CODE REVIEW

**Comment by nali** [comment]
Should neutral just have the light off @carlos-dev ? Makes sense, no?

**Comment by xarlio** [comment]
yup, makes sense. Im going to do the icon grey

**Comment by xarlio** [comment]
@nali updated

**Comment by epallerols** [comment]
👍

**Comment by nali** [comment]
Looks good!

**Pull request merged**
